version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres
   restart: always
   env_file:
    - .env
   ports:
    - "5432:5432"
   volumes:
    - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin
   restart: always
   env_file:
    - .env
   ports:
    - "8080:80"
   volumes:
    - pgadmin-data:/var/lib/pgadmin

volumes:
 db-data:
 pgadmin-data: