version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  backend:
    container_name: backend_api
    build: backend/
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend_vue
    build: frontend/


volumes:
 db-data:
 pgadmin-data: